# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_pb2 as client__pb2


class GetTopicsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTopics = channel.unary_unary(
                '/grpc.GetTopics/GetTopics',
                request_serializer=client__pb2.Word.SerializeToString,
                response_deserializer=client__pb2.Topics.FromString,
                )


class GetTopicsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetTopics(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetTopicsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopics,
                    request_deserializer=client__pb2.Word.FromString,
                    response_serializer=client__pb2.Topics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.GetTopics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetTopics(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.GetTopics/GetTopics',
            client__pb2.Word.SerializeToString,
            client__pb2.Topics.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
