# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x63lient.proto\x12\x04grpc\"#\n\x05Topic\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"%\n\x06Topics\x12\x1b\n\x06topics\x18\x01 \x03(\x0b\x32\x0b.grpc.Topic\"\x14\n\x04Word\x12\x0c\n\x04Word\x18\x01 \x01(\t24\n\tGetTopics\x12\'\n\tGetTopics\x12\n.grpc.Word\x1a\x0c.grpc.Topics\"\x00\x62\x06proto3'
)




_TOPIC = _descriptor.Descriptor(
  name='Topic',
  full_name='grpc.Topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.Topic.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.Topic.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=57,
)


_TOPICS = _descriptor.Descriptor(
  name='Topics',
  full_name='grpc.Topics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='grpc.Topics.topics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=96,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='grpc.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Word', full_name='grpc.Word.Word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=118,
)

_TOPICS.fields_by_name['topics'].message_type = _TOPIC
DESCRIPTOR.message_types_by_name['Topic'] = _TOPIC
DESCRIPTOR.message_types_by_name['Topics'] = _TOPICS
DESCRIPTOR.message_types_by_name['Word'] = _WORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Topic)
  })
_sym_db.RegisterMessage(Topic)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), {
  'DESCRIPTOR' : _TOPICS,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Topics)
  })
_sym_db.RegisterMessage(Topics)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Word)
  })
_sym_db.RegisterMessage(Word)



_GETTOPICS = _descriptor.ServiceDescriptor(
  name='GetTopics',
  full_name='grpc.GetTopics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTopics',
    full_name='grpc.GetTopics.GetTopics',
    index=0,
    containing_service=None,
    input_type=_WORD,
    output_type=_TOPICS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETTOPICS)

DESCRIPTOR.services_by_name['GetTopics'] = _GETTOPICS

# @@protoc_insertion_point(module_scope)
