# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cserver.proto\x12\x04grpc\"\x14\n\x04Text\x12\x0c\n\x04Text\x18\x01 \x01(\t\"a\n\x06\x41nswer\x12(\n\x06result\x18\x01 \x03(\x0b\x32\x18.grpc.Answer.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32\x36\n\nFilterText\x12(\n\nFilterText\x12\n.grpc.Text\x1a\x0c.grpc.Answer\"\x00\x62\x06proto3'
)




_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='grpc.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='grpc.Text.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_ANSWER_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='grpc.Answer.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.Answer.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.Answer.ResultEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=141,
)

_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='grpc.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.Answer.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ANSWER_RESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=141,
)

_ANSWER_RESULTENTRY.containing_type = _ANSWER
_ANSWER.fields_by_name['result'].message_type = _ANSWER_RESULTENTRY
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Text)
  })
_sym_db.RegisterMessage(Text)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANSWER_RESULTENTRY,
    '__module__' : 'server_pb2'
    # @@protoc_insertion_point(class_scope:grpc.Answer.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Answer)
  })
_sym_db.RegisterMessage(Answer)
_sym_db.RegisterMessage(Answer.ResultEntry)


_ANSWER_RESULTENTRY._options = None

_FILTERTEXT = _descriptor.ServiceDescriptor(
  name='FilterText',
  full_name='grpc.FilterText',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=143,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='FilterText',
    full_name='grpc.FilterText.FilterText',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_ANSWER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILTERTEXT)

DESCRIPTOR.services_by_name['FilterText'] = _FILTERTEXT

# @@protoc_insertion_point(module_scope)
